language: ruby
rvm:
- '2.3.3'
- '2.4.1'
sudo: false
cache: bundler
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
addons:
  postgresql: '9.4'
install: bin/setup
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9e19170ed7c12fb33a8d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
